### ISSUE TITLE
Parsing of dates using the Hermes JS engine causes failures

### ISSUE THREAD

**Issue by shokimble** [Alex61NN5/get-fiscal-year#14]
It is not recommended to use date strings in the Date() constructor due to inconsistencies between browsers and JS engines.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#several_ways_to_create_a_date_object

I will submit a PR for this issue.

**Comment by Alex61NN5** [comment]
@shokimble that would be great!

**Comment by Alex61NN5** [comment]
@shokimble I will test and make sure its all working and then merge 😊
